analyzer:
  exclude:
    - build/**
    - android/**
    - ios/**
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    always_declare_return_types: true
    always_use_package_imports: true
    avoid_print: true
    directives_ordering: true
    prefer_const_constructors: true
    prefer_const_declarations: true
    prefer_final_locals: true
    prefer_initializing_formals: false
    prefer_single_quotes: true
    require_trailing_commas: true
    sort_child_properties_last: true
